
quarkus.application.name=ms_order
quarkus.http.port=8087

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=bodgen
quarkus.datasource.password=bodgen123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bodgendb

# Desactivar base de datos temporal de Quarkus (Dev Services)
quarkus.datasource.devservices.enabled=false

# Configuración de Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Opcional: Para ver los valores de los parámetros en el log de SQL
quarkus.hibernate-orm.log.bind-parameters=true
