
quarkus.application.name=ms_order
quarkus.http.port=8087

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=bodgen
quarkus.datasource.password=bodgen123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bodgendb

# Desactivar base de datos temporal de Quarkus (Dev Services)
quarkus.datasource.devservices.enabled=false

# Configuración de Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Opcional: Para ver los valores de los parámetros en el log de SQL
quarkus.hibernate-orm.log.bind-parameters=true

# Redis
redis.host=redis://localhost:6379
redis.pool.size=64
redis.pool.minIdle=10
redis.timeout=3000
redis.connectTimeout=10000

# caches
cache.order.name=ORDER_MAP
cache.order.prefix=ORDER_
cache.order.ttl=180

quarkus.rest-client.product-api.url=http://localhost:8086

# Circuit Breaker
quarkus.fault-tolerance."org.mpravia.proxy.service.ProductClientService/getProductsByCode".circuit-breaker.request-volume-threshold=5
quarkus.fault-tolerance."org.mpravia.proxy.service.ProductClientService/getProductsByCode".circuit-breaker.failure-ratio=0.5
quarkus.fault-tolerance."org.mpravia.proxy.service.ProductClientService/getProductsByCode".circuit-breaker.delay=10

# Timeout
quarkus.fault-tolerance."org.mpravia.proxy.service.ProductClientService/getProductsByCode".timeout.value=2000

# Retry
quarkus.fault-tolerance."org.mpravia.proxy.service.ProductClientService/getProductsByCode".retry.max-retries=4
quarkus.fault-tolerance."org.mpravia.proxy.service.ProductClientService/getProductsByCode".retry.delay=500

quarkus.log.category."io.smallrye.faulttolerance".level=DEBUG